# .air.toml
[build]
cmd = "go build -o /tmp/app ./"
bin = "/tmp/app"
full_bin = "APP_ENV=dev /tmp/app"
include_ext = ["go"]
exclude_dir = ["vendor", "tmp"]
exclude_file = ["*_test.go"]
follow_symlink = true
delay = 1000

[log]
level = "debug"
color = "true"
timestamp = "true"

[watch]
full = "false"
include = ["./"]
exclude = ["vendor", "tmp"]